# 推送到coding
script:
  - git config user.name "ayuayue"
  - git config user.email "1401262639@qq.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  git push --force --quite "https://18737001259:{WHnwvORRxx}@e.coding.net/caoayu/caoayu.git"
  # git push --force --quite "https://{GIT_TOKEN}@github.com/ayuayue/ayuayue.github.io.git"

# End: Build LifeCycle
